version: '3.7'

services:
  dog-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=1234
      - DB_NAME=dogs_db
      - PORT=3000
      - DATABASE_URL='postgresql://postgres:1234@db:5432/mydb?schema=public'
        # - DATABASE_URL=postgresql://postgres:1234@db:5432/mydb?schema=public
    volumes:
      - ./src:/home/node/app/src
    container_name: dog-app
    ports:
      - '3000:3000'
    depends_on:
      - db
    command: npm run dev #start
    restart: always

  #postgres database
  db:
    image: postgres
    restart: always #unless-stopped
    environment:
      # - POSTGRES_HOST: localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_NAME=dogs_db
      - POSTGRES_DB=dogs_db
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db_queries/create_db.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./db_queries/create_drop_db.sql:/docker-entrypoint-initdb.d/create_drop_db.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
